accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('settings/changeUsername/', views.settings, name='changeUsername'),
    path('settings/changePassword/', views.settings, name='changePassword'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('signup/', views.register, name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('classes', views.classList, name='classes'),
    path('class/<pk>', views.classView, name='classView'),
    path('assignment/<pk>', views.assignmentView, name='assignmentView'),
]

coonva/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('app.urls')),
	path('', include('accounts.urls'))
]

templates/405.html
{% extends 'css.html' %}

{% block title %}Page Not Allowed{% endblock %}

{% block page_content %}
<div style="text-align: center">
    <br>
    <h1>Error 405</h1>
    <br>
    <h1>You're not supposed to be here</h1>
    <h4>This page can't be accessed like this<br><a class="button" href="{% url 'app:index' %}">Head on back to the Homepage</a></h4>
	<a class="button" href="{% url 'app:bugReport' %}"><b>Submit a bug report.</b></a>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Coonva{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<script src="{% static 'script.js' %}"></script>
	{% block extra_head %}{% endblock %}
</head>

<div class="sidenav">
	{% if user.is_authenticated %}
		<img class='profile_pic' width="75" height="75" src={{ user.profile_image.url }}></img>
		<h3>{{ user.username.upper }}</h3>
	{% endif %}
	<a href="{% url "app:index" %}"> Home</a>
	<a href="{% url "accounts:settings" %}"> Settings</a>
	<a href="{% url "app:classes" %}">Classes</a>
	<a href="#clients">Clients</a>
	<a href="#contact">Contact</a>
	{% block sidebar%}
	{% endblock sidebar %}
</div>


<body class="main">
<div id="toast-container"></div>
<div class="navbar">
	<h1>{% block heading %}{% endblock heading %}</h1>

	{% if user.is_authenticated %}
		<navbar-buttons>
			<form method="post" action="{% url 'accounts:logout' %}">
				{% block extra_navbar %}{% endblock extra_navbar %}
				{% csrf_token %}
				<button type="submit">Logout</button>
				{% if user.is_staff %}
					<a class="button" href="/admin">Admin Site</a>
				{% endif %}
			</form>
		</navbar-buttons>
	{% else %}
	<navbar-buttons>
		<form>
			<a class="button" href="{% url 'accounts:login' %}">Login</a>
			<a class="button" href="{% url 'accounts:register' %}">Sign Up</a>
		</form>
	</navbar-buttons>
	{% endif %}
</div>
{% block page_content %}
{% endblock page_content %}
	
</body>

</html>

templates/login.html
<head>    
    <meta charset="utf-8">
    <title>{% block page_title %}YubTub{% endblock page_title %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<form method="post">
    <h2>Login</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  <p>Don't have an account? <a href="{% url 'accounts:register' %}">Register here</a>.</p>
</form>

templates/register.html
<head>    
    <meta charset="utf-8">
    <title>{% block page_title %}YubTub{% endblock page_title %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>