app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('classes', views.classList, name='classes'),
    path('class/<pk>', views.classView, name='classView'),
    path('assignment/<pk>', views.assignmentView, name='assignmentView'),
]

coonva/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('app.urls')),
	path('', include('accounts.urls'))
]

app/templates/app/assignment.html
{% extends 'base.html' %}

{% block heading %}{{assignment.name}}{% endblock %}

{% block page_content %}
{{ assignment.details }}

{{assignment.type}}

<h3>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
		{{ assignment }}<br><br>
	{% if assignment.type == 'URL' %}
		Link Upload: 
		{{ form.URL }}
	{% elif assignment.type == 'FILE' %}
		File Upload<br>
		{{ form.file }}
	{% elif assignment.type == 'TEXT' %}
		Details<br>
		{{ form.text }}
	{% endif %}
	<br><button type="submit">Submit</button>
</form>
</h3>

{% endblock page_content %}

app/templates/app/class.html
{% extends 'base.html' %}

{% block heading %}{{ class.title }}{% endblock %}

{% block page_content %}
<div class="grid-container">
{% for i in assignments %}
{% if user not in i.submitted.all %}
<class onclick="window.location.href='{% url "app:assignmentView" i.pk %}'">
	<name>{{i.name}}</name>
	{{i.details}}
</class>
{% endif %}
{% endfor %}
</div>
{% endblock %}

app/templates/app/classList.html
{% extends 'base.html' %}

{% block page_content %}


<div class="grid-container">
{% for class in classes %}
<class  onclick="window.location.href='{% url "app:classView" class.pk %}'">
	<name>{{class.title}}</name>
	{{class.teachers.get}}
</class>
{% endfor %}
</div>

{% endblock page_content %}

app/templates/app/index.html
{% extends "base.html" %}
{% load static %}
{% block extra_static %}
<script src="{% static "jsTests/script.js" %}" type="module" ></script>
{% endblock extra_static %}



{% block sidebar %}
<a href='#test'>Test</a>
<a href='#thing'>Thing
{% endblock sidebar %}

{% block page_content %}
<button onclick="showToast('success', 'This is a toast message!')">Show Toast</button>
{% endblock page_content %}